apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: http
  - port: 3306
    protocol: TCP
    name: mysq
  - port: 2222
    protocol: TCP
    name: ssh

  selector:
    minion: stage
