apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus3-stage-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/sonatype-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-stage-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
