CREATE DATABASE IF NOT EXISTS gogs CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER 'git'@'%' IDENTIFIED BY 'only4gogs';
GRANT ALL PRIVILEGES ON gogs.* TO 'git'@'%' WITH GRANT OPTION;
SET default_storage_engine=INNODB;
FLUSH PRIVILEGES;
EXIT

