apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 32128

  selector:
    app: sonarqube
