version: '3.1'

services:

  db:
    build: stage/mysql/
    container_name: 'mysql-compose'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    networks:
      - test-net

  gogs:
    build: stage/gogs/
    container_name: 'gogs-compose'
    networks:
      - test-net
    ports:
      - 3000:3000
    links:
      - "db"

networks:
    test-net:
      driver: bridge

