apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-stage-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/gogs-repositories"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-stage-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
